#nome do workflow
name: CI-CD

# controle de como o workflow vai executar
on:
  # Gatilhos de requisições de "push" ou "pull" que vão fazer o workflow executar
  push:
    branches: [ "main" ]

  # Permite executar o workflow manualmente
  workflow_dispatch:

# Um workflow é composto de um ou mais jobs que podem executar em sequencia ou em paralelo
jobs:
  # JOB de CI
  CI:
    # O Job vai rodar em um sistema linux ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Autenticando o usuário do docker
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Construindo a imagem e enviado para o dockerhub
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            ices/kube-news:latest
            ices/kube-news:v${{github.run_number}}
  
  CD:
      runs-on: ubuntu-latest
      needs: [CI]
      steps:
        - uses: actions/checkout@v3

        - name: Definindo o Kube config
          uses: azure/k8s-set-context@v2
          with:
            method: kubeconfig
            kubeconfig: ${{secrets.AKS_CONFIG}}
        
        - name: Efetuando o deploy no Kubernetes
          uses: Azure/k8s-deploy@v3.1
          with:
            images: ices/kube-news:v${{github.run_number}}
            manifests: k8s/deployment.yaml